services:
  app:
    build:
      context: .
      dockerfile: Dockerfile   # <── now uses local Dockerfile
    image: pollapp:latest
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
